name:  ğŸ’„ PHP Lint
on: push

jobs:
  build:
    name: Run Linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./users-management

    steps:
      - name: ğŸ“‚ Checkout
        uses: actions/checkout@v4

      - name: ğŸ Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_pgsql
          coverage: none

      - name: â¬ Install dependencies
        run: |
          composer install -n --prefer-dist
          composer require laravel/pint --dev

      - name: ğŸ’„ Run Pint
        run: |
          ./vendor/bin/pint --test


  # ./vendor/bin/pint






