name:  ğŸ’„ PHP Lint
on: push

jobs:
  build:
    name: Run Linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./users-management

    steps:
      - name: ğŸ“‚ Checkout
        uses: actions/checkout@v3

      - name: ğŸ Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_pgsql
          coverage: none

      - name: â¬ Install dependencies
        run: |
          composer install -n --prefer-dist
          # pip install ruff

      # - name: ğŸ’„ Run Ruff
      #   run: |
      #     ruff check --output-format=github .
      #     ruff format --check .
          